[tool.ruff]
line-length = 80
extend-include = ["*.ipynb"]
extend-exclude = ["notebooks/after.py", "notebooks/before.py"]

[tool.ruff.lint]
ignore = ["E402"]

# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"